# Generated by Django 3.1.5 on 2021-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20210311_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.CharField(choices=[('choice1', 'choice2A'), ('choice 22', 'choice2333')], max_length=200),
        ),
    ]
