# Generated by Django 3.1.5 on 2021-03-12 01:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('quizapp', '0004_auto_20210311_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
