# Generated by Django 3.1.5 on 2021-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20210312_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.TextField(),
        ),
    ]
