# Generated by Django 3.1.5 on 2021-03-20 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
